# Generated by Django 2.2.2 on 2019-07-08 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='questionnaire.QuestionnaireAnswer'),
        ),
        migrations.AlterField(
            model_name='questionnairefield',
            name='max_val',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnairefield',
            name='min_val',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnairefield',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnairefield',
            name='text_after',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
